CREATE TABLE IF NOT EXISTS address
(
    id    SERIAL NOT NULL PRIMARY KEY ,
    text  VARCHAR(256) NOT NULL ,
    zip  VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS building
(
    id    SERIAL NOT NULL PRIMARY KEY ,
    date  VARCHAR(256) NOT NULL ,
    type  VARCHAR(256) NOT NULL
);